##################################################
# Node Endpoints
##################################################

# List aggregated nodes
GET http://localhost:3333/nodes

# List aggregated nodes with applied allowlist
GET http://localhost:3333/nodes?allowlistId=1

# List aggregated nodes with applied allowlist inverted
GET http://localhost:3333/nodes?allowlistId=1&invert=true

# List Nodes for a source 
GET http://localhost:3333/sources/1


##################################################
# Allowlist Endpoints
##################################################

# List all allowlists
GET http://localhost:3333/allowlist

# Create an allowlist
POST http://localhost:3333/allowlist
Content-Type: application/json

{
    "name": "Default"
}


# Delete an allowlist
DELETE http://localhost:3333/allowlist/1

# List IPs in an allowlist
GET http://localhost:3333/allowlist/1/entry

# Add an IP to an allowlist
POST http://localhost:3333/allowlist/1/entry
Content-Type: application/json

{
    "cidr": "2.58.0.0/16"
}

# Add an IP to an allowlist
POST http://localhost:3333/allowlist/1/entry
Content-Type: application/json

{
    "cidr": "192.168.0.0/16"
}

# Remove an IP from an allowlist
DELETE http://localhost:3333/allowlist/1/entry/1


##################################################
# Source Endpoints
##################################################

# List Sources
GET http://localhost:3333/sources

# Create the udger source to run every minute
POST http://localhost:3333/sources
Content-Type: application/json

{
    "name": "udger",
    "url": "https://raw.githubusercontent.com/udger/test-data/master/CSV_data_example/tor_exit_node.csv",
    "period": "00:01:00"
}

# Create the dan.me.uk source to run every 30 minutes
POST http://localhost:3333/sources
Content-Type: application/json

{
    "name": "dan.me.uk",
    "url": "https://www.dan.me.uk/torlist/?exit",
    "period": "00:30:00"
}

# Create the dan.me.uk source to run every 30 seconds
POST http://localhost:3333/sources
Content-Type: application/json

{
    "name": "mock",
    "url": "http://localhost:3334/data1.csv",
    "period": "00:00:30"
}

# Stop a Source and removes all its nodes from the system
POST http://localhost:3333/sources/1/stop

# Queues up the source to start syncing again
POST http://localhost:3333/sources/1/start



