// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: allowlist.sql

package database

import (
	"context"
)

const addToAllowlist = `-- name: AddToAllowlist :one
INSERT INTO allowlist_entry (ip_addr, list_id) 
VALUES ($1, $2)
ON CONFLICT (ip_addr, list_id) 
DO NOTHING
RETURNING id, ip_addr, list_id
`

type AddToAllowlistParams struct {
	IpAddr string
	ListID int32
}

func (q *Queries) AddToAllowlist(ctx context.Context, arg AddToAllowlistParams) (AllowlistEntry, error) {
	row := q.db.QueryRow(ctx, addToAllowlist, arg.IpAddr, arg.ListID)
	var i AllowlistEntry
	err := row.Scan(&i.ID, &i.IpAddr, &i.ListID)
	return i, err
}

const createAllowList = `-- name: CreateAllowList :one
INSERT INTO allowlist (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateAllowList(ctx context.Context, name string) (Allowlist, error) {
	row := q.db.QueryRow(ctx, createAllowList, name)
	var i Allowlist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteAllowList = `-- name: DeleteAllowList :exec
DELETE FROM allowlist
WHERE id = $1
`

func (q *Queries) DeleteAllowList(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAllowList, id)
	return err
}

const listEntriesForAllowList = `-- name: ListEntriesForAllowList :many
SELECT DISTINCT ip_addr
FROM allowlist_entry 
WHERE list_id = $1
ORDER BY ip_addr
`

func (q *Queries) ListEntriesForAllowList(ctx context.Context, listID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listEntriesForAllowList, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ip_addr string
		if err := rows.Scan(&ip_addr); err != nil {
			return nil, err
		}
		items = append(items, ip_addr)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromAllowlist = `-- name: RemoveFromAllowlist :exec
DELETE FROM allowlist_entry 
WHERE ip_addr = $1
AND list_id = $2
`

type RemoveFromAllowlistParams struct {
	IpAddr string
	ListID int32
}

func (q *Queries) RemoveFromAllowlist(ctx context.Context, arg RemoveFromAllowlistParams) error {
	_, err := q.db.Exec(ctx, removeFromAllowlist, arg.IpAddr, arg.ListID)
	return err
}
