// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Allowlist struct {
	ID   int32
	Name string
}

type AllowlistEntry struct {
	ID     int32
	IpAddr string
	ListID int32
}

type Node struct {
	ID       int32
	IpAddr   string
	SourceID int32
	Version  pgtype.Int8
}

type Source struct {
	ID            int32
	Name          string
	Url           string
	Period        pgtype.Interval
	LastExecution pgtype.Timestamp
	Version       pgtype.Int8
	Running       pgtype.Bool
}
